---  # squawk User configuration file

app:
  loglevel: INFO
  check_for_updates: true
  update_check_url: "https://github.com/in03/squawk" # If you fork the repo, change this to your fork

resolve:
  subtitle_folder_path: "/Assets/subtitles"

paths:
  working_dir: R:/Squawk  # Where to store transcription working files

text_to_speech:
  model: small # [tiny, small, medium, large] - larger models are more accurate
  translate_to_english: True
  words_per_screen: 15 # Limit the amount of words on screen at a time